-- print("This ran before.")
-- print()
-- print(vim.inspect(vim.opt.runtimepath))
-- print(vim.inspect(vim.opt.packpath))

-- print(vim.o.runtimepath:find(vim.env.VIMRUNTIME) ~= nil)
-- -- vim.o.runtimepath:prepend(vim.env.VIMRUNTIME)
-- print(vim.o.runtimepath:find(vim.env.VIMRUNTIME) ~= nil)

-- print(vim.env.VIMRUNTIME)
-- vim.opt.runtimepath:prepend(vim.env.VIMRUNTIME)
-- print(vim.o.runtimepath:find(vim.env.VIMRUNTIME, 1, true) ~= nil)

-- print(vim.inspect(vim.opt.runtimepath))
-- print(vim.inspect(vim.opt.packpath))

VERBOSE = false
SAFE = true
LAYERS = nil

local selections = { -- used to ensure mutual exclusivity of conflicting plugins
	picker = "snacks",
	top_line = "dropbar", -- dropbar|nougat|minibar|winbar
	bottom_line = "lualine", -- lualine|nougat|cokeline|heirline|galaxyline|staline|windline
	tab_line = "bufferline", -- bufferline|tabby|nougat
}

USING = {
	ai = {
		["copilot"] = true,
		["opencode"] = true,
		["avante"] = true,
		["codecompanion"] = true,
		["llm"] = true,
		["vim-ai"] = true,
		["sg"] = true,
	},
	checks = {
		["rg"] = true,
	},
	clipboard = {
		["general"] = true,
		["autocommands"] = true,
		["yanky"] = true,
		["lazyclip"] = true,
		["pasta"] = true,
		["wastebin"] = true,
	},
	cloud = {
		["kubectl"] = true,
		["kpops"] = true,
		["kubels"] = true,
		["vim-helm"] = true,
		["k8vim"] = true,
		["kubernetes"] = true,
	},
	colors = {
		["odenwald-colorscheme"] = true,
		["headlines"] = true,
		["sunglasses"] = true,
		["configure"] = true,
	},
	completion = {
		["friendly-snippets"] = true,
		["ultisnips"] = true,
		["luasnip"] = true,
		["nvim-cmp"] = true,
		["blink-cmp"] = true,
	},
	debugging = {
		["dapui"] = true,
		["dap-virtual-text"] = false, -- false: fix dependency
		["keymaps"] = true,
		["autommands"] = true,
	},
	diff = {
		["diffview"] = true,
	},
	editing = {
		["general-setup"] = true,
		["vim-commentary"] = true,
		["Comment"] = true,
		["todo-comments"] = true,
		["ts_context_commentstring"] = true,
		["savior"] = true,
		["vim-auto-save"] = true,
		["zpragmatic"] = false,
		["multicursors"] = false, -- TODO: rebuild
		["vim-visual-multi"] = true,
		["illuminate"] = true,
		["splitjoin"] = false, -- TODO: debug
		["spread"] = false, -- TODO: update (using old nvim-treesitter)
		["treesj"] = true,
		["Bullets"] = true,
		["sort"] = true,
		["ax"] = true,
		["vim-caser"] = true,
		["wrapping"] = true,
		["wrapping-paper"] = true,
		["dotdot"] = false, -- TODO: debug
		["vim-abolish"] = true,
		["date-time-inserter"] = true,
		["switch.vim"] = true,
		["dial"] = false, -- TODO: debug
		["moveline"] = true,
		["sibling-swap"] = false, -- TODO: rebuld
		["move"] = true,
		["wildfire"] = true,
		["vim-sandwich"] = true,
		["mini.surround"] = true,
		["ultimate-autopair"] = true,
		["blink.pairs"] = true,
		["rainbow-delimiters"] = true,
		["nvim-autopairs"] = true,
		["nvim-surround"] = true,
		["mini.pairs"] = true,
		["better-digraphs"] = false, -- TODO: debug
		["indent-blankline"] = true,
		["indent-tools"] = false, -- TODO: debug
		["tabular"] = true,
		["indentmini"] = true,
		["mini.indentscope"] = true,
		["anydent"] = true,
		["nvim-anydent"] = true,
		["mini.align"] = true,
		["vim-mundo"] = true,
		["edit-list"] = false, -- TODO: fix import error
		["various-textobjs"] = true,
		["miscellaneous-autocommands"] = true,
	},
	execution = {
		["conjure"] = true,
		["sniprun"] = true,
		["live-command"] = true,
		["channelot"] = true,
		["vim-slime"] = true,
		["jaq"] = true,
		["iron"] = true,
		["resin"] = true,
		["officer"] = true,
		["compiler"] = true,
		["jupytext"] = true,
		["quarto"] = true,
		["asyncrun"] = true,
		["xmake"] = true,
	},
	experimental = {
		["fsread"] = false,
		["wezterm-run"] = false,
		["consilium"] = false,
	},
	explorers = {
		["yazi"] = true,
		["oil"] = true,
		["neotree"] = true,
		["nvimtree"] = true,
		["chadtree"] = false,
	},
	folding = {
		["configure_folding"] = true,
		["ufo"] = false, -- TODO: fix async name collision
	},
	git = {
		["octo"] = false,
		["octohub"] = false,
		["worktrees"] = false,
		["forgit"] = false,
		["official-gitlab"] = false,
		["gitlab"] = false,
		["gitsigns"] = false,
		["jj"] = false,
		["jujutsu"] = false,
		["jiejie"] = false,
		["lazygit"] = false,
		["git-conflict"] = false,
		["neogit"] = false,
		["vim-fugitive"] = false,
		["blame"] = false,
	},
	lsp = {
		["general-setup"] = true,
		["create-keymaps"] = true,
		["create-autocommands"] = true,
		["diagflow"] = true,
		["configure-diagnostics-modes"] = true,
		["conform"] = true,
		["lsp-format"] = true,
		["lspkind"] = true,
		["lspsaga"] = true,
		["doc-window"] = false, -- TODO: update to remove dep on nvim-treesitter.ts_utils
		["trouble"] = true,
		["quicker"] = true,
		["bqf"] = true,
		["nvim-lint"] = true,
		["refactoring"] = true,
		["error-jump"] = true,
		["qfview"] = true,
		["vale"] = true,
		["genghis"] = true,
		["precommit"] = true,
		["lint"] = true,
		["corn"] = true,
		["glance"] = true,
		["dmap"] = true,
		["strict"] = false,
		["inlayhint-filler"] = true,
		["hlargs"] = true,
		["lsp_signature"] = true,
		["nvim-lightbulb"] = true,
	},
	macros = {
		["neocomposer"] = true,
		["nvim-macros"] = true,
		["recorder"] = true,
	},
	mappings = {
		["general_keymaps"] = false,
		["keyseer"] = true,
		["homerows"] = true,
		["whichkey-setup"] = true,
		["better-escape"] = true,
		["which-key"] = true,
		["mini-keymap"] = true,
		["hydra"] = true,
		["insx"] = true,
		["keymap-amend"] = true,
		["unimpaired-which-key"] = true,
		["wf"] = false,
		["keytex"] = true,
		["nvim-keymapper"] = true,
		["mini-keymap"] = true,
		["hawtkeys"] = true,
	},
	miscellaneous = {
		["Launch"] = false,
		["minimal-narrow-region"] = false,
		["telemake"] = false,
		["nvim-api-wrappers"] = false,
		["wezterm-nvim"] = false,
		["advanced_new_file"] = false,
		["tracebundler"] = false,
		["present"] = false,
		["wezterm-move"] = false,
		["move-mode"] = false,
		["runtimetable"] = false,
		["structlog"] = false,
		["tealmaker"] = false,
		["cmdTree"] = false,
		["pommodoro-clock"] = false,
		["pomodoro"] = false,
		["timerly"] = false,
		["timew"] = false,
		["nomodoro"] = false,
		["sche"] = false,
		["twig"] = false,
		["dashboard-nvim"] = false,
		["dashboard"] = false,
		["fsplash"] = false,
		["drop"] = false,
		["doing"] = false,
		["vimwiki"] = false,
		["obsidian"] = false,
		["orgmode"] = false,
		["zettelkasten"] = false,
		["flote"] = false,
		["scratch-buffer"] = false,
		["neowell-lua"] = false,
		["quicknote"] = false,
		["nvim-highlight-colors"] = false,
		["text-to-colorscheme"] = false,
		["minty"] = false,
		["color-picker"] = false,
		["baleia"] = false,
		["easycolor"] = false,
		["export-colorscheme"] = false,
		["bamboo"] = false,
		["kreative"] = false,
		["mini.hipatterns"] = false,
		["paint"] = false,
		["carbon-now-nvim"] = false,
		["showkeys"] = false,
		["hypersonic"] = false,
		["regexplainer"] = false,
		["tldr"] = false,
		["nvim-luaref"] = false,
		["auto-pandoc"] = false,
		["nerdy"] = false,
		["cyrillic"] = false,
		["xkbswitch"] = false,
		["http-codes"] = false,
		["live-server"] = false,
		["web-tools"] = false,
		["api-browser"] = false,
		["metrics"] = false,
		["keylab"] = false,
		["nvim-apm"] = false,
		["daily-focus"] = false,
		["interlaced"] = false,
		["nvmm"] = false,
		["feed"] = false,
		["firenvim"] = false,
		["qalc"] = false,
		["flashcards"] = false,
		["nvim-license"] = false,
	},
	multilang = {
		["knap"] = true,
		["nvim-quicktype"] = true,
		["femaco"] = true,
		["otter"] = true,
	},
	navigation = {
		["general-setup"] = true,
		["spear"] = true,
		["smart-splits"] = true,
		["swm"] = true,
		["nvim_winpick"] = false, -- TODO: write nix expression to build rust
		["windows"] = false, -- TODO: fix config error
		["pragma"] = true,
		["windex-nvim"] = true,
		["bafa"] = true,
		["flybuf"] = true,
		["vuffers"] = true,
		["retrospect"] = true,
		["stickybuf"] = true,
		["spaceport-nvim"] = true,
		["beam"] = true,
		["navigator"] = true,
		["vim-wordmotion"] = true,
		["clever-f"] = true,
		["hop"] = true,
		["mini.jump"] = true,
		["mini.jump2d"] = true,
		["neowords"] = true,
		["leap"] = true,
		["flash"] = true,
		["treemonkey"] = true,
		["vim-edgemotion"] = true,
		["whaler"] = true,
		["marks"] = true,
		["harpoon-core"] = true,
		["markit"] = true,
		["arrow"] = true,
		["gx-extended"] = true,
		["urlview"] = true,
		["highlight-current-n"] = true,
	},
	projects = {
		["auto_session"] = true,
		["persistence"] = true,
		["project"] = true,
		["mini_sessions"] = true,
		["projector"] = true,
		["neoconf"] = true,
	},
	search = {
		["ido"] = true,
		["regex-vars"] = false,
		["inc_rename"] = false,
		["muren"] = false,
		["rip-substitute"] = false,
		["sad"] = false,
		["fzf-lua"] = false,
		["deck"] = false,
		["snacks"] = false, -- selections.picker == "snacks",
		["hlslens"] = false,
		["nvim-hlsearch"] = false,
		["grug-far"] = false,
		["spectre"] = false,
		["pickme"] = selections.picker == "pickme",
		["renamer"] = false,
		["search-replace"] = false,
		["rgflow"] = false,
		["ssr"] = false,
		["substitute"] = false,
		["actions-preview"] = false,
		["spider"] = false,
		["improved-search-nvim"] = false,
		["nvim-rg"] = false,
		["hlsearch-nvim"] = false,
		["nvim-monorepos"] = false,
		["blink"] = false,
		["replacer"] = false,
	},
	task_runner = {
		["overseer"] = false,
		["custom_telescope"] = false,
		["moonicipal"] = false,
	},
	telescope_etc = {
		["telescope"] = true,
	},
	terminal = {
		["create_keymaps"] = true,
		["vim-floaterm"] = true,
		["toggleterm"] = true,
		["neaterm"] = true,
		["termim"] = true,
		["yarepl"] = true,
		["neomux"] = true,
	},
	testing = {
		["neotest"] = true,
		["coverage"] = true,
	},
	treesitter = {
		["set-global-ts-languages"] = true,
		["general-setup"] = true,
		["check-parsers"] = true,
		["configure-filetypes-and-aliases"] = true,
		["configure-folds-and-indentation"] = true,
		["nvim-treesitter-textobjects"] = true,
		["treesitter-context"] = true,
		["wrap-treesitter-start"] = true,
		["change-commands"] = true,
		["create-autocommands"] = true,
	},
	ui = {
		["nvim-web-devicons"] = true,
		["virtcolumn"] = false,
		["virt-column"] = false,
		["smartcolumn"] = false,
		["statuscol"] = false,
		["TreePin"] = false,
		["symbols"] = true,
		["aerial"] = false,
		["navbuddy"] = false,

		["bufferline"] = selections.tab_line == "bufferline",
		["tabby"] = selections.tab_line == "tabby",
		["nougat::tabline"] = selections.tab_line == "nougat",

		["dropbar"] = selections.top_line == "dropbar",
		["nougat::winbar"] = selections.top_line == "nougat",
		["minibar"] = selections.top_line == "minibar",
		["winbar"] = selections.top_line == "winbar",

		["lualine"] = selections.bottom_line == "lualine",
		["nougat::statusline"] = selections.bottom_line == "nougat",
		["cokeline"] = selections.bottom_line == "cokeline",
		["heirline"] = selections.bottom_line == "heirline",
		["galaxyline"] = selections.bottom_line == "galaxyline",
		["staline"] = selections.bottom_line == "staline",
		["windline"] = selections.bottom_line == "windline",

		["navic"] = false,
		["vimade"] = false,
		["zen-mode"] = true,
		["modicator"] = true,
		["modes"] = true,
		["cmdbuf"] = false,
		["mini.cmdline"] = false,
		["menu"] = false,
		["fidget"] = true,
		["notify"] = false,
		["control-panel"] = false,
		["output-panel"] = false,
		["cosmic-ui"] = false,
		["lvim-ui-config"] = false,
		["volt"] = false,
		["noice"] = false,
		["reactive"] = false,
	},
}

function setup_all_enabled(modname, funcset)
	toggles = USING[modname]

	for name, func in pairs(funcset) do
		if toggles[name] then
			func()
		end
	end
end
